package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Template struct{ID int64 `json:"id"`;Name string `json:"name"`;Channel string `json:"channel"`;Subject string `json:"subject"`;Body string `json:"body"`;CreatedAt time.Time `json:"created_at"`}
type Send struct{ID int64 `json:"id"`;TemplateID int64 `json:"template_id"`;Recipient string `json:"recipient"`;Status string `json:"status"`;SentAt time.Time `json:"sent_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"notify.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS templates(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,channel TEXT DEFAULT 'sms',subject TEXT DEFAULT '',body TEXT NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS sends(id INTEGER PRIMARY KEY AUTOINCREMENT,template_id INTEGER NOT NULL,recipient TEXT NOT NULL,status TEXT DEFAULT 'queued',sent_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)CreateTemplate(t *Template)error{res,err:=db.Exec(`INSERT INTO templates(name,channel,subject,body)VALUES(?,?,?,?)`,t.Name,t.Channel,t.Subject,t.Body);if err!=nil{return err};t.ID,_=res.LastInsertId();return nil}
func(db *DB)ListTemplates()([]Template,error){rows,_:=db.Query(`SELECT id,name,channel,subject,body,created_at FROM templates ORDER BY created_at DESC`);defer rows.Close();var out[]Template;for rows.Next(){var t Template;rows.Scan(&t.ID,&t.Name,&t.Channel,&t.Subject,&t.Body,&t.CreatedAt);out=append(out,t)};return out,nil}
func(db *DB)RecordSend(s *Send){res,_:=db.Exec(`INSERT INTO sends(template_id,recipient,status)VALUES(?,?,?)`,s.TemplateID,s.Recipient,s.Status);s.ID,_=res.LastInsertId()}
func(db *DB)ListSends(templateID int64)([]Send,error){rows,_:=db.Query(`SELECT id,template_id,recipient,status,sent_at FROM sends WHERE template_id=? ORDER BY sent_at DESC LIMIT 100`,templateID);defer rows.Close();var out[]Send;for rows.Next(){var s Send;rows.Scan(&s.ID,&s.TemplateID,&s.Recipient,&s.Status,&s.SentAt);out=append(out,s)};return out,nil}
func(db *DB)DeleteTemplate(id int64){db.Exec(`DELETE FROM sends WHERE template_id=?`,id);db.Exec(`DELETE FROM templates WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var t,s int;db.QueryRow(`SELECT COUNT(*) FROM templates`).Scan(&t);db.QueryRow(`SELECT COUNT(*) FROM sends`).Scan(&s);return map[string]interface{}{"templates":t,"total_sends":s},nil}
